services:
  mysql:
    image: 'mysql:8.4'
    container_name: shiftplanner-mysql
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: verysecret
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/var/lib/mysql'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pverysecret"]
      interval: 5s
      timeout: 3s
      retries: 20
  backend:
    build:
      context: ./backend
    container_name: shiftplanner-backend
    depends_on:
      mysql:
          condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: mysql,dev  # dev f√ºr die initialen Testuser
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydatabase?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      JWT_SECRET: your-256-bit-secret-goes-here-change-this
      JWT_EXPIRATION: "86400000"
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    container_name: shiftplanner-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
volumes:
  mysql_data: